import numpy as np
import matplotlib.pyplot as plt

fitness1  = np.load("data/fitness1.npy")
fitness2  = np.load("data/fitness2.npy")
fitness3  = np.load("data/fitness3.npy")
fitness4  = np.load("data/fitness4.npy")
fitness5  = np.load("data/fitness5.npy")
fitness6  = np.load("data/fitness6.npy")
fitness7  = np.load("data/fitness7.npy")
fitness8  = np.load("data/fitness8.npy")
fitness9  = np.load("data/fitness9.npy")
fitness10 = np.load("data/fitness10.npy")
plt.plot(fitness1, label="Trial 1",linewidth=1)
plt.plot(fitness2, label="Trial 2",linewidth=1)
plt.plot(fitness3, label="Trial 3",linewidth=1)
plt.plot(fitness4, label="Trial 4",linewidth=1)
plt.plot(fitness5, label="Trial 5",linewidth=1)
plt.plot(fitness6, label="Trial 6",linewidth=1)
plt.plot(fitness7, label="Trial 7",linewidth=1)
plt.plot(fitness8, label="Trial 8",linewidth=1)
plt.plot(fitness9, label="Trial 9",linewidth=1)
plt.plot(fitness10, label="Trial 10",linewidth=1)
plt.title("Fitness over Generations")
plt.xlabel("Generation")
plt.ylabel("abs(fitness)")
plt.legend(bbox_to_anchor=(1.05, 1.0), loc='upper left')
plt.tight_layout()
#plt.show()
plt.savefig('fitnessPlot.png')